class Adjective < Generator
  # Exquisite adjectives (http://www.dailywritingtips.com/100-exquisite-adjectives/)
  EXQUISITE = {
    "adamant" => "unyielding; a very hard substance",
    "adroit" => "clever, resourceful",
    "amatory" => "sexual",
    "animistic" => "quality of recurrence or reversion to earlier form",
    "antic" => "clownish, frolicsome",
    "arcadian" => "serene",
    "baleful" => "deadly, foreboding",
    "bellicose" => "quarrelsome (its synonym belligerent can also be a noun)",
    "bilious" => "unpleasant, peevish",
    "boorish" => "crude, insensitive",
    "calamitous" => "disastrous",
    "caustic" => "corrosive, sarcastic; a corrosive substance",
    "cerulean" => "sky blue",
    "comely" => "attractive",
    "concomitant" => "accompanying",
    "contumacious" => "rebellious",
    "corpulent" => "obese",
    "crapulous" => "immoderate in appetite",
    "defamatory" => "maliciously misrepresenting",
    "didactic" => "conveying information or moral instruction",
    "dilatory" => "causing delay, tardy",
    "dowdy" => "shabby, old-fashioned; an unkempt woman",
    "efficacious" => "producing a desired effect",
    "effulgent" => "brilliantly radiant",
    "egregious" => "conspicuous, flagrant",
    "endemic" => "prevalent, native, peculiar to an area",
    "equanimous" => "even, balanced",
    "execrable" => "wretched, detestable",
    "fastidious" => "meticulous, overly delicate",
    "feckless" => "weak, irresponsible",
    "fecund" => "prolific, inventive",
    "friable" => "brittle",
    "fulsome" => "abundant, overdone, effusive",
    "garrulous" => "wordy, talkative",
    "guileless" => "naive",
    "gustatory" => "having to do with taste or eating",
    "heuristic" => "learning through trial-and-error or problem solving",
    "histrionic" => "affected, theatrical",
    "hubristic" => "proud, excessively self-confident",
    "incendiary" => "inflammatory, spontaneously combustible, hot",
    "insidious" => "subtle, seductive, treacherous",
    "insolent" => "impudent, contemptuous",
    "intransigent" => "uncompromising",
    "inveterate" => "habitual, persistent",
    "invidious" => "resentful, envious, obnoxious",
    "irksome" => "annoying",
    "jejune" => "dull, puerile",
    "jocular" => "jesting, playful",
    "judicious" => "discreet",
    "lachrymose" => "tearful",
    "limpid" => "simple, transparent, serene",
    "loquacious" => "talkative",
    "luminous" => "clear, shining",
    "mannered" => "artificial, stilted",
    "mendacious" => "deceptive",
    "meretricious" => "whorish, superficially appealing, pretentious",
    "minatory" => "menacing",
    "mordant" => "biting, incisive, pungent",
    "munificent" => "lavish, generous",
    "nefarious" => "wicked",
    "noxious" => "harmful, corrupting",
    "obtuse" => "blunt, stupid",
    "parsimonious" => "frugal, restrained",
    "pendulous" => "suspended, indecisive",
    "pernicious" => "injurious, deadly",
    "pervasive" => "widespread",
    "petulant" => "rude, ill humored",
    "platitudinous" => "resembling or full of dull or banal comments",
    "precipitate" => "steep, speedy",
    "propitious" => "auspicious, advantageous, benevolent",
    "puckish" => "impish",
    "querulous" => "cranky, whining",
    "quiescent" => "inactive, untroublesome",
    "rebarbative" => "irritating, repellent",
    "recalcitant" => "resistant, obstinate",
    "redolent" => "aromatic, evocative",
    "rhadamanthine" => "harshly strict",
    "risible" => "laughable",
    "ruminative" => "contemplative",
    "sagacious" => "wise, discerning",
    "salubrious" => "healthful",
    "sartorial" => "relating to attire, especially tailored fashions",
    "sclerotic" => "hardening",
    "serpentine" => "snake-like, winding, tempting or wily",
    "spasmodic" => "having to do with or resembling a spasm, excitable, intermittent",
    "strident" => "harsh, discordant; obtrusively loud",
    "taciturn" => "closemouthed, reticent",
    "tenacious" => "persistent, cohesive,",
    "tremulous" => "nervous, trembling, timid, sensitive",
    "trenchant" => "sharp, penetrating, distinct",
    "turbulent" => "restless, tempestuous",
    "turgid" => "swollen, pompous",
    "ubiquitous" => "pervasive, widespread",
    "uxorious" => "inordinately affectionate or compliant with a wife",
    "verdant" => "green, unripe",
    "voluble" => "glib, given to speaking",
    "voracious" => "ravenous, insatiable",
    "wheedling" => "flattering",
    "withering" => "devastating",
    "zealous" => "eager, devoted"
  }

  VALUES =
    # Favorites
    %w(
     turbo
     shady
     stupendous
     sacred
     deadly
     silent
     ethereal
     ultra
    ) +
    EXQUISITE.keys
end